### ISSUE TITLE
host mustadio on github pages

### ISSUE THREAD

**Issue by yet-another-lucas** [yet-another-lucas/mustadio#4]
I think we can do this https://pages.github.com so nobody has to clone and run the code to see what it does.

**Comment by lunzhang** [comment]
I don't think github pages can run server sided code.

**Comment by yet-another-lucas** [comment]
@lunzhang That's very possible. If you have a citation or proof I'll go ahead and close out this issue. Thanks!

**Comment by lunzhang** [comment]
Heres the link.  https://help.github.com/articles/what-is-github-pages/

**Comment by yet-another-lucas** [comment]
@lunzhang ++ thanks for that, totally clear now.
