### ISSUE TITLE
Write a code of conduct

### ISSUE THREAD

**Issue by yet-another-lucas** [yet-another-lucas/mustadio#7]
Another good hacktoberfest idea: `Consider adopting a code of conduct to foster a greater sense of community.`

**Comment by abrahamhurtado** [comment]
What do you think of the Covenant Code of Conduct? It's one of the most popular around, Rails has it iirc.

Another option would be the [TODO Code of Conduct](http://todogroup.org/opencodeofconduct/) which Facebook took as a base for [theirs](https://code.facebook.com/pages/876921332402685/open-source-code-of-conduct).

**Comment by yet-another-lucas** [comment]
@abrahamhurtado I think the Covenant Code of Conduct sounds very heavy handed and legalese. The facebook however seems very authentic and real. Thanks for those links!

**Comment by abrahamhurtado** [comment]
Glad to be helpful! Do you mind if I send a pull request adding the code of conduct? Or we should wait a bit to get more input?

**Comment by yet-another-lucas** [comment]
@abrahamhurtado Hmm should probably wait. In hindsight maybe this isn't a good hacktoberfest candidate.

**Comment by abrahamhurtado** [comment]
¯\_(ツ)_/¯

**Comment by yet-another-lucas** [comment]
this is now complete
