### ISSUE TITLE
dropdown page

### ISSUE THREAD

**Issue by yet-another-lucas** [yet-another-lucas/mustadio#9]
A page with a select input.

Ones that immediately come to mind:
```
basic html select
the dreaded select2
```

We can always add more later as we think of them.

**Comment by anmol27katyani** [comment]
What exactly do you want @yet-another-lucas ?

**Comment by yet-another-lucas** [comment]
@octamois Thanks for the question. This project has various pages. This page would be like those, however it's contents would be a normal html dropdown menu and a select2 dropdown menu. I hope that is more clear.
